id: A0910EC8F
base_file: f5600.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:26:32.290614
  last_modified_at: 2022-06-17 11:26:32.290618
