id: A0910EC8F
base_file: f8A3A.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:26:32.298280
  last_modified_at: 2022-06-17 11:26:32.298283
