id: A0910EC8F
base_file: f2C00.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:26:32.287810
  last_modified_at: 2022-06-17 11:26:32.287813
