id: A0910EC8F
base_file: fC1CE.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:26:32.308958
  last_modified_at: 2022-06-17 11:26:32.308961
