id: A0910EC8F
base_file: f581B.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:26:32.292309
  last_modified_at: 2022-06-17 11:26:32.292312
