id: A0910EC8F
base_file: f1B7B.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:26:32.286120
  last_modified_at: 2022-06-17 11:26:32.286126
