id: A0910EC8F
base_file: fAB80.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:26:32.303885
  last_modified_at: 2022-06-17 11:26:32.303888
